name: report-generation

on:
  push:
    paths:
      - report/**
    branches:
      - report
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Pandoc
        run: sudo apt-get install -y -qq pandoc

      - name: Install LaTeX
        run: sudo apt-get install -y -qq texlive texlive-latex-extra


      - name: Generate PDF, Commit and push changes
        run: |
          mkdir -p report/build
          pandoc $(ls report/*.md | sort) -s -o report/build/MSc_group_h.pdf
          git add -f report/build/MSc_group_h.pdf
          git commit -m "Generate PDF from Markdown files"
          git push origin report
          gh pr create --title "Generate PDF from Markdown files" --body "This PR generates a PDF from the Markdown files in the report directory." --base main
          gh pr merge --squash --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
